### ISSUE TITLE
cran windows build errors

### ISSUE THREAD

**Issue by edzer** [r-quantities/units#136]
See [here](https://win-builder.r-project.org/dyv1i4X8UPxn/00install.out) - @t-kalinowski do you have an idea what is going on? (I should have noted when I'd listened to [appveyor](https://ci.appveyor.com/project/edzer/units/build/1.0.288))

**Comment by t-kalinowski** [comment]
Unfortunately, I don't have access to a windows box presently, so I can't test this. 

But, looking at the logs, my only guess is that it's some kind of path separator issue and
```
system.file("share/udunits2.xml", package="units")
```
[here](https://github.com/r-quantities/units/blob/master/R/valid_udunits.R#L15) should probably be changed to

```
system.file("share", "udunits2.xml", package="units")
```

**Comment by Enchufa2** [comment]
There is no problem with the slash. I just checked it in a Windows VM and the problem is that the file is not under `share/udunits2.xml`, but under `share/udunits/udunits2.xml`. On Windows, the installation substitutes `inst/share` with the `share` found in the udunits2 library, which has this structure. So I think that the easiest solution is to mimic that structure.
