### ISSUE TITLE
best practice: integrate xts-units-vector over time?

### ISSUE THREAD

**Issue by dleutnant** [r-quantities/units#201]
Hi all, 
I am working on a project where I need to integrate an `xts` matrix over time (cf. the example below).  I'm aware that the `units` package is not compatible with the `xts` class and thus, I'm wondering whether there is a best practice/recommendation to make the best of both worlds? 

Consider the following example: A time series with runoff data [L/s] is given. Time series data are occasionally non-equidistant. The objective is to get the total runoff volume [m3] within a specific period. 

The code constructs an `xts`-object, has a method to create a `list` object which contains the `xts` data and the required time differences and finally has a new `sum` function. 

``` r
suppressPackageStartupMessages(library(units))
suppressPackageStartupMessages(library(xts))
library(magrittr)

# create dummy data (index with 1 min frequency) 
# Meausurement unit is "L/s", integrating the whole period yields to 900 Liter.
x <- xts::xts(x = c(2, 1, 4, 5, 3), 
              order.by = Sys.time() + 1:5 * 60)

# split xts object into 3-element list which contains the time-deltas 
as_unitslist <- function(x, ...)  {

  index <- zoo::index(x)
  delta <- units::as_units(diff(index))
  delta <- c(delta[1], delta) # add one index
  values <- units::as_units(zoo::coredata(x), ...)
  
  units_list <- list(index = index,    # vector: original index 
                     delta = delta,    # vector: index diffs as 'units' 
                     values = values)  # matrix: original values as  'units'
  
  # introduce new class
  class(units_list) <- c(class(units_list), "unitslist")
  units_list
}

# generic sum function dispatches to object of class unitslist
sum.unitslist <- function(x, ...) {
  sum(x$delta * x$values, ...)
}

# execution
x %>% 
  as_unitslist("L/s") %>% 
  sum()
#> 900 [L]
```

<sup>Created on 2019-04-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Is there a better/easier way to achieve this?
Any support and/or feedback is greatly appreciated! 
Thank you!

**Comment by edzer** [comment]
I like the idea to some extent; we're running in many similar issues in the [stars](https://github.com/r-spatial/stars) project (but mostly with space integrals). A problem is that AFAICT `xts` objects have no semantics for (i) whether observations belong to a time instance or to a time interval, and (ii) what the length of the last time interval is when the time series is irregular. In case you'd go wrong with (i), your time integral is wrong. Time integration is something else as summing values with units; one would need data structures that are more explicit to do this, I'm afraid. When you know stuff, as you show, it's trivial to do with `units`. 

Having `xts` and `units` play together will be difficult because `xts` objects are time (row) indexed numeric matrices. Have you looked at `tsibble`, perhaps a more modern and flexible alternative?

**Comment by dleutnant** [comment]
Thank you, @edzer!

`xts` objects are charming because of i) simplicity (cf. subsetting methods) and ii) efficiency (matrix structure underneath). The latter obviously fires back in terms of flexibility. `tsibble`s offer great flexibility due to `tibble` backed data structure which of course allows `units` vectors as columns (I am not starting the dependency discussion here...).
Both classes, however, do not intrinsically solve the time integration issue. Having a robust vector class ([vctrs](https://github.com/r-lib/vctrs)?!) for this would be nice.

> "...one would need data structures that are more explicit to do this..."

I agree.  I'll do some experiments...

**Comment by dleutnant** [comment]
As I see that my current project does not allow to further investigate a holistic "units-based integration" approach, I created a [gist](https://gist.github.com/dleutnant/81045313c87177484b7d7b9e4584594f) to share how I would integrate objects of class `xts` and `tsibble` over time. Maybe this could be a starting point to further developments and eventually helps others. @edzer Please feel free to close this issue for now.

**Comment by Enchufa2** [comment]
Closing this for now.
