### ISSUE TITLE
Error: package or namespace load failed for ‘units’ in dyn.load(file, DLLpath = DLLpath, ...):

### ISSUE THREAD

**Issue by wangzhongkai1** [r-quantities/units#288]
Dear Enchufa2, 
Thanks for your  nice work on R-quantities, especially on Units package, whereas I have some errors below while the package is installing on the loading phase, **knowing that libudunits2.so** has been installed correctly. Could you please help me debugging this problem? Thank you again and looking forward to your reply!

```
** testing if installed package can be loaded from temporary location
Error: package or namespace load failed for ‘units’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/hwfssz5/ST_MCHRI/DISEASE/single_cell/software_myt/R_diff_version/R-4.0.1/library/00LOCK-units/00new/units/libs/units.so':
  libudunits2.so.0: cannot open shared object file: No such file or directory
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/hwfssz5/ST_MCHRI/DISEASE/single_cell/software_myt/R_diff_version/R-4.0.1/library/units’
Warning message:
In install.packages("/hwfssz5/ST_MCHRI/DISEASE/single_cell/software_myt/R_diff_version/R-4.0.1/build/tmp/units_0.7-2.tar.gz") :
  installation of package ‘/hwfssz5/ST_MCHRI/DISEASE/single_cell/software_myt/R_diff_version/R-4.0.1/build/tmp/units_0.7-2.tar.gz’ had non-zero exit status
```

**Comment by Enchufa2** [comment]
Correctly installed where? It's obvious from the path strings that you have a non-standard installation. If you have done the same for UDUNITS2 and other libraries, then this is a matter of R administration with non-standard locations. See the [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#External-software) guide, or, otherwise, the R-help mailing list would be a better place for this.
