### ISSUE TITLE
Installation error on Mac 

### ISSUE THREAD

**Issue by dcaud** [r-quantities/units#300]
installing from source failed:

`install.packages("units", type="source")`

but this worked:

`install.packages("units")`

**Comment by Enchufa2** [comment]
Failed how? This package interfaces the udunits C library, so to compile from source, the proper toolchain as well as the development files for this library are required. The package is on CRAN and has prebuilt binaries available for this platform (as you already confirmed), which means that installation from source works just fine. I recommend using those prebuilt binaries. Otherwise, if you have a non-standard setup, the [R-SIG-Mac](https://stat.ethz.ch/mailman/listinfo/r-sig-mac) mailing list is the proper place to ask for help.
