### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by ilikegitlab** [r-quantities/units#367]
After a recent update of ggplot2:
>data.frame(a=c(1,2,3),b=set_units(c(4,4,3),"m")) |> ggplot() + geom_point(aes(a,b))
Warning message:
The `scale_name` argument of `continuous_scale()` is deprecated as of ggplot2 3.5.0.
This warning is displayed once every 8 hours.
Call `lifecycle::last_lifecycle_warnings()` to see where this warning was generated. 

I only get this when using units.

**Comment by edzer** [comment]
Thanks!

**Comment by edzer** [comment]
@Enchufa2 this seems to break `quantities` checks in GA, but that might well be false negatives?

**Comment by Enchufa2** [comment]
> @Enchufa2 this seems to break `quantities` checks in GA, but that might well be false negatives?

Sorry, didn't see this message. Kind of. A ggplot2 test fails because the resulting SVG is a little different, but there's no visual difference. I updated the test in quantities and pinned it to this version of units, but we'll need to release quantities before units the next time to avoid CRAN issues. No big deal.
