### ISSUE TITLE
Error: In ‘g/kg’ the numeric multiplier ‘0.001’ is invalid

### ISSUE THREAD

**Issue by samuel-rosa** [r-quantities/units#91]
In version 0.4-6 of `units`, when setting the measurement unit of a quantity as `g/kg`, the quantity used to be multiplied by `0.001` to achieve simplification, returning a unitless quantity. Now, with version 0.5-1, the following error message is thrown:

```r
> library(units)
> x <- 1.3
> set_units(x, g/kg)
Error: In ‘g/kg’ the numeric multiplier ‘0.001’ is invalid. 
Use `install_conversion_constant()` to define a new unit that is a multiple of another unit.
> 
> install_conversion_constant(from = "g", to = "kg", const = 1/1000)
> install_conversion_constant(from = "kg", to = "g", const = 1000)
> 
> set_units(x, g/kg)
Error: In ‘g/kg’ the numeric multiplier ‘0.001’ is invalid. 
Use `install_conversion_constant()` to define a new unit that is a multiple of another unit.
```

Although the behaviour in the current version seems a bug that may need a fix (I am not sure about this), I would like to know how to avoid the simplification of units. The unit `g/kg` is extensively used in my field (soil science) and it is very important that it be kept as is when used with a quantity.

I have seen that `units` throws the error message above every time we use a unit composed of physically related units: `g/kg`, `mL/L`, and so on.

I think that there is some discussion about this in http://www.sciencedirect.com/science/article/pii/S0263224117303305.

**Comment by t-kalinowski** [comment]
In the example above, are `g` and `kg` referring to different things? For example, grams arsenic / kg soil? Or are they referring to the same thing (g soil / g soil). 

If it's the former, i wonder if instead of `install_conversion_constant`, this problem would be better addressed through `install_symbolic_unit()`, or something like it.

**Comment by edzer** [comment]
Whatever it is, this is a regression introduced in 0.5-0. 

SI units primarily don't address the _of what_ question. The enhancement @samuel-rosa points to is a proposal to further specify dimensionless units, so that e.g. `rad`, counts of persons, and `g/g` units are no longer convertible.

**Comment by t-kalinowski** [comment]
Agreed, I was just thinking of where and how this usage might be accommodated. I don't think simply removing the error check in `as_units` is the right solution.

**Comment by samuel-rosa** [comment]
@t-kalinowski, I am working with quantities of elements in the soil such as grams of arsenic per kilogram of soil. I am not sure if I understood your suggestion to use `install_symbolic_unit`. Is it as follows?

```r
> library(units)
> install_symbolic_unit("g/kg")
Warning message:
In install_symbolic_unit("g/kg") :
  ‘g/kg’ is already a valid unit recognized by udunits.
Installation not necessary and is not performed
```

I think that @edzer has made my suggestion clearer.

**Comment by t-kalinowski** [comment]
Oh, `install_symbolic_unit()` won’t work for this yet. I was speaking more towards future development efforts and how best to accommodate this use case. 

What do you think of introducing syntax like this to address this use case: 
```
install_symbolic_unit("g_arsenic")
install_symbolic_unit("kg_soil")
make_units(g_arsenic / kg_soil)
```

**Comment by edzer** [comment]
I think the only way is to have `as_units("kg/g")` return `1000 1`, i.e. 1000 unitless, and use the 1000 as multiplier in `units<-`.

**Comment by samuel-rosa** [comment]
@t-kalinowski I think that your suggestion is inappropriate for my needs. Maybe I need to explain it a bit.

We have recently launched a soil data repository in Brazil (http://coral.ufsm.br/febr/). Soil data is stored using the very same measurement units used in the source. This means that you have different measurement units for the same variable across different datasets. We have also created an R package to download the data. Because data from different datasets must be stacked, measurement units need to be standardized. Here is where I was planning to use `units`. Because there are hundreds of soil variables available, creating variable-specific measurement units would soon result in something quite hard to manage (managing the data is already a lot of work).

Unfortunately I have no idea on how to help with this enhancement. But I think that many will benefit from it.

**Comment by t-kalinowski** [comment]
This syntax will work w/ the current CRAN version:
``` r
x <- as_units("g/kg", force_single_symbol = TRUE)
y <- as_units("mg/kg", force_single_symbol = TRUE)
z <- as_units("ug/kg", force_single_symbol = TRUE)

c(x, y, z)
#> Units: (g/kg)
#> [1] 1e+00 1e-03 1e-06
x+y+z
#> 1.001001 (g/kg)
```

**Comment by samuel-rosa** [comment]
Thank you @t-kalinowski, but I hope you can come up soon with `units_options(simplify_units = FALSE)`.

**Comment by edzer** [comment]
This patch gives us again
```r
# udunits system database read

# Attaching package: ‘units’

# The following object is masked from ‘package:base’:

#     %*%

x <- set_units(1, g/kg)
y <- set_units(1, mg/kg)
z <- set_units(1, ug/kg)

c(x, y, z)
# Units: 1
# [1] 1e-03 1e-06 1e-09
```
The next thing would be to keep track that this is a g/g unitless unit, which one couldn't meaningfully add to a `rad` or `m/m` - at least that is how I understand the Flater papers.

**Comment by t-kalinowski** [comment]
The current solution appears to not be working properly. With the current udunits branch:

``` r
library(units)

# user has two vectors, wants to normalize both to the one unit, then drop units
x <- set_units(1, ug/kg)
y <- set_units(1, mg/kg)
combined <- set_units(c(x, y), mg/kg)
drop_units(combined) 
#> [1] 1e-15 1e-12
# should be 0.001, 1
```

Let me preface that I have not read the Flater paper yet beyond the abstract, so I'm just thinking about this narrow use-case of enabling creating units like "mg/kg" and doing unit conversion with those units.  

My impression from the Flater abstract is that it seems like a comprehensive and principled solution that will take some work to implement, and if or until that gets implemented here, we should have an interim solution that enables just this minimal subset of functionality.

I think the root cause of the bug in the code example above is that currently, units like "mg/kg" change the numeric value of the vector being assigned units.  Please reconsider #94 which does not modify the numeric value.

**Comment by edzer** [comment]
The fact that we now have
```r
> (x = set_units(1, mg/kg))
1e-06 1
```
is not a bug, but is inherent to simplification: units cancel, prefixes propagate to the value. When a user next expects that
```r
> set_units(x, ug/kg)
1e-15 1
```
has units `ug/kg`, then this user has not understood unitless values, nor what unit simplification entails.

My resolution to this "issue" is, as @samuel-rosa suggested, to provide the option to suppress all simplification, as in:
```r
library(units)
# udunits system database from /usr/share/xml/udunits
units_options(simplify = FALSE)
(x = set_units(1, mg/kg))
# 1 mg/kg
(y = set_units(1, ug/kg))
# 1 ug/kg
x + y
# 1.001 mg/kg
y + x
# 1001 ug/kg
```
This is in https://github.com/r-quantities/units/commit/bb380a33c597a3b44a309f3980b1db50f8c8004b.

**Comment by t-kalinowski** [comment]
let me describe how I first came to use this package.
In my previous job I frequently worked with environmental data that looked like this:

``` 
Location_ID,   chemical_name, value, value_units
      loc_1, Trichloroethene,    20,      ug/l
      loc_1,  Vinyl Chloride,  19.2,      mg/l
      loc_2, Trichloroethene,    20,  UG/LITER
      loc_2,  Vinyl Chloride,  13.2,      μg/l
```

The key take away is that the units were specified in a wide variety of ways in the source data, and I used this package to standardize the whole table to be one consistent set of units. And in that regard it was very helpful because it allowed me to cover a wide variety of edge cases just with 
``` R
df %>% 
  split_by(value_units) %>%
  lapply(function(.df) {
    within(.df, {
      units(value) <- value_units 
      units(value) <- value_units <- TARGET_VALUE_UNIT
      units(value) <- NULL
    })
  }) %>% 
  bind_rows()
```
This is altogether not that different a use case from @samuel-rosa's, except he was dealing with soil data and therefor encountered this issue of units like mg/kg canceling out first. I mostly dealt with groundwater data, and soil data only occasionally (though, i would have run into that issue eventually).

So the statement 
> user has not understood unitless values, nor what unit simplification entails

 is not relevant to the above use case, because the theory behind unitless objects is not relevant to the format of the data.

I'm glad the option to not simplify was added (I wasn't aware of that until you pointed it out). I suggest that the option be defaulted to FALSE within the unit constructor and unit converter, and TRUE everywhere else.

**Comment by edzer** [comment]
I think that makes a lot of sense. Please review whether these changes, still in a branch called simplifysometimes, do what you have in mind.

**Comment by t-kalinowski** [comment]
Thanks! This is exactly what I had in mind.

My one suggestion is to use `on.exit()` to restore the option, so that the option is still restored if an error is thrown.

**Comment by edzer** [comment]
OK, thanks! Shall I then proceed, merge with udunits, and merge udunits into master?

**Comment by t-kalinowski** [comment]
sounds good to me.

**Comment by samuel-rosa** [comment]
Many thanks for this improvement. I will let you know if I find any problem.
