### ISSUE TITLE
passing pointer from R -> Cpp -> R not working

### ISSUE THREAD

**Issue by t-kalinowski** [r-quantities/units#95]
``` r
library(units)
#> udunits system database from /usr/local/share/udunits
#> 
#> Attaching package: 'units'
#> The following object is masked from 'package:base':
#> 
#>     %*%
units:::ud_are_convertible("20 * s", "seconds since 1970-01-01")
#> Error in R_ut_are_convertible(R_ut_parse(as.character(u1)), R_ut_parse(as.character(u2))): external pointer is not valid
```

**Comment by Enchufa2** [comment]
Let me take a look,

**Comment by edzer** [comment]
Remove the spaces around the `*`:
```r
> units:::R_ut_parse("20*s")
<pointer: 0x5571c247b230>
```

**Comment by edzer** [comment]
... or write no, one or multiple spaces to imply multiplication:
```r
> units:::R_ut_parse("20*s")
<pointer: 0x55d67debea80>
> units:::R_ut_parse("20s")
<pointer: 0x55d67d8cb650>
> units:::R_ut_parse("20 s")
<pointer: 0x55d67c83a820>
> units:::R_ut_parse("20  s")
<pointer: 0x55d67c84e290>
```
all mean the same.

**Comment by Enchufa2** [comment]
Yeap, but the thing is... why are we returning `XPtr`s at all? Each time you get a pointer to a `ut_unit`, it is a clone of an internal object. At R level, we should work with names and symbols only.

**Comment by Enchufa2** [comment]
Check #98, please.

**Comment by edzer** [comment]
Of course we can do without, as that is what we've done so far. It's an experiment, and still in an early phase. With Xptr, you can do
```r
> units:::R_ut_format(units:::R_ut_parse("20*s"))
[1] "20 s"
```
where you wouldn't have to redo the parse for every print. Also, convert after checking conversion is possible, can now be done without parsing both units _twice_.

Now before you are going to tell me that these operation have negligible cost, please provide some pointers to large computations where indeed doing units did not have a cost overhead. [This](http://r-spatial.org/r/2017/11/13/perp-performance.html) post gave me worries that units may involve overhead,  but I still have to go to the bottom of it.

**Comment by t-kalinowski** [comment]
re @edzer's first suggestions for alternative syntax: all good suggestions but if `"20 * m"` is not valid then `ut_is_parseable()` should reflect that.

**Comment by Enchufa2** [comment]
@edzer I'm not going to say that the cost is negligible. But in any case, this is how udunits works: it protects the internal representation by returning clones always. This means that you always have to parse, or get_unit_by something, unless you have a _parallel_ representation of the units system, i.e., you extract _all_ unit objects and you have them mapped in some kind of hash table. But that means to completely reimplement udunits...

For example, there is no gain in `R_ut_scale()` returning an `XPtr` if you are not saving it for later use in a hash table. Because if the external pointer is not saved, R finalises it in the same way as if you call `ut_free` in `R_ut_scale()` and return void. Moreover, returning an `XPtr` has the extra cost of constructing the `XPtr` itself!

As I see it, the only reasonable use case for `XPtr` here may be what you just mentioned: formatting, but only if `R_ut_format` is going to be called multiple times over the same `R_ut_parse` output. Otherwise... `XPtr` introduces more overheads.

**Comment by edzer** [comment]
It now returns `FALSE` as it should; looks like a bug in udunit2, since ut_parse returns `NULL` while `ut_get_status()` returns `UT_SUCCESS`.
```r
> units:::ud_is_parseable("20 * m")
[1] FALSE
> udunits2::ud.is.parseable("20 * m")
[1] FALSE
```

**Comment by Enchufa2** [comment]
Then idependently of whether you decide to merge #98 or not, this issue can be closed.

**Comment by Enchufa2** [comment]
Well... `units:::ud_are_convertible("20 * s", "seconds since 1970-01-01")` still throws an error instead of returning `FALSE`. I'm not sure what's the desired output though.
